# Generated by Django 2.2.7 on 2020-11-15 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('profile_path', models.TextField(null=True)),
                ('ko_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tagdatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_tagdatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('tagdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Tagdatas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(null=True)),
                ('poster_url', models.TextField(null=True)),
                ('release_date', models.CharField(max_length=30, null=True)),
                ('rating', models.BooleanField()),
                ('searchdata', models.TextField()),
                ('actors', models.ManyToManyField(related_name='movie_actor', to='movies.Actor')),
                ('genres', models.ManyToManyField(related_name='movie_genre', to='movies.Genres')),
                ('tagdatas', models.ManyToManyField(related_name='movie_tagdatas', to='movies.Tagdatas')),
                ('user_dib', models.ManyToManyField(related_name='movie_user_dib', to=settings.AUTH_USER_MODEL)),
                ('user_like', models.ManyToManyField(related_name='movie_user_like', to=settings.AUTH_USER_MODEL)),
                ('user_watched', models.ManyToManyField(related_name='movie_user_watched', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
